apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "metatoc-ui.fullname" . }}
  labels:
    {{- include "metatoc-ui.labels" . | nindent 4 }}
data:
  default.conf: |-
    server {
        listen       80;

      location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
          try_files $uri $uri/ /index.html;
      }

      location /api {
        rewrite ^.+api/?(.*)$ /$1 break;
        include uwsgi_params;
        proxy_pass {{ .Values.nginxConf.apiPassProxy }};
      }
    }
